require 'erb'
require 'json'
require 'em-websocket'
require 'base64'
require_relative 'shenmegui/core'
require_relative 'shenmegui/controls'
require_relative 'shenmegui/file_dialog'
require_relative 'shenmegui/utils'
